spring.application.name=Ga-me






#port number
server.port=8888

#Context Path
server.servlet.context-path= /

#Log level
#error>warn>info>debug>trace
logging.level.root=info


# ======
# ?????? mysql ??
# =======

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/???????useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.url=jdbc:mysql://localhost:3306/mydb

# DB?? ??
spring.datasource.username=root
spring.datasource.password=WLDNJS0825

#ORM??? ??(object)? ??? ??????(RDBMS)? ???? ???? ??
#jpa??
#   ??? ?? orm ?????
#   ??? ??? ??????? ??? ??,???? ??? ????
#   ????? ??? ??? db???? ???? ??? ??

#Hibernate
#JPA? ??? ORM ???
#??? : ???? ???? ?? / ????? ????? sql? ?? / ??? ?? ? ???? ? ..

#jpa, hibernate ??
#sql? ??? ??(??? ?? ???)
spring.jpa.show-sql=true
# DDL ?? ??/?? ??
#- validate : ???? ??? ??? ??? ?? ??(?? ??)
#- update : ??? ????? db ??? ????(??/???)
#- none : ?? ?? ??? ?? ??
spring.jpa.hibernate.ddl-auto=validate

#Hibernate? SQL? ?? ??? ? ???? ?? ??????? Dialect(??)? ???? ??
#DB???? SQL ??/ ?? / ??? ?? ?? ??? ???
#???? DB(MYSQL,Oracle,MariaDB .. ? )? ?? Dialect? ???? ??? sql? ???
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


#???? sql ???? ??
spring.jpa.properties.hibernate.format_sql=true
# ?? ?????? ???? Hibernate ??
logging.level.org.hibernate.type.descriptor.sql=trace